import { test, expect } from "@playwright/test"
import { installStressSessionTabs, installTimelineSettings, mockStressTimeline } from "./timeline-test-helpers"

test("artifact panel has an explicit entry, usable tabs, errors and no horizontal overflow", async ({ page }) => {
  await mockStressTimeline(page)
  await installTimelineSettings(page)
  await installStressSessionTabs(page)
  await page.goto("/")
  const welcome = page.getByRole("region", { name: "What will we create today?" })
  await welcome.getByRole("textbox").fill("Show artifacts")
  await welcome.getByRole("button", { name: "Continue to session" }).click()
  await page.locator('a[href*="ses_smoke_source"]').first().click()
  await page.getByRole("button", { name: "查看成果", exact: true }).click()
  const panel = page.getByLabel("成果面板", { exact: true })
  await expect(panel.getByText("在这里查看成果")).toBeVisible()
  await panel.getByRole("textbox").fill("demo.html")
  await panel.getByRole("button", { name: "打开", exact: true }).click()
  await expect(panel.getByRole("tab", { name: "demo.html", exact: true })).toBeVisible()
  await expect(panel.getByRole("alert")).toContainText("桌面端")
  await panel.getByRole("textbox").fill("http://localhost:3000/second")
  await panel.getByRole("button", { name: "打开", exact: true }).click()
  await expect(panel.getByRole("tab", { name: "second", exact: true })).toHaveAttribute("aria-selected", "true")
  await panel.getByRole("tab", { name: "demo.html", exact: true }).click()
  await expect(panel.getByRole("tab", { name: "demo.html", exact: true })).toHaveAttribute("aria-selected", "true")
  await panel.getByRole("button", { name: "关闭 demo.html", exact: true }).click()
  await expect(panel.getByRole("tab", { name: "second", exact: true })).toHaveAttribute("aria-selected", "true")
  await page.locator('button[aria-controls="review-panel"]').first().click()
  await expect(panel).toBeHidden()
  await page.getByRole("button", { name: "查看成果", exact: true }).click()
  await expect(panel.getByRole("tab", { name: "second", exact: true })).toBeVisible()
  await page.locator('a[href*="ses_smoke_target"]').first().click()
  await page.getByRole("button", { name: "查看成果", exact: true }).click()
  await expect(panel.getByText("在这里查看成果")).toBeVisible()
  await page.locator('a[href*="ses_smoke_source"]').first().click()
  await page.getByRole("button", { name: "查看成果", exact: true }).click()
  await expect(panel.getByRole("tab", { name: "second", exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: "../../quality/artifact-panel.png" })
})
