import { expect, test } from "@playwright/test"
import { installStressSessionTabs, installTimelineSettings, mockStressTimeline } from "./timeline-test-helpers"

test("welcome keeps task text when opening the real session composer", async ({ page }) => {
  await mockStressTimeline(page)
  await installTimelineSettings(page)
  await installStressSessionTabs(page)
  await page.goto("/")
  const welcome = page.getByRole("region", { name: "What will we create today?" })
  await expect(welcome.getByRole("img", { name: "Zaovra" })).toBeVisible()
  await expect(page.locator(".home-library")).toHaveCount(0)
  await welcome.getByRole("button", { name: "Projects", exact: true }).click()
  await expect(page).toHaveURL(/view=projects/)
  await expect(welcome).toHaveCount(0)
  await expect(page.locator(".home-library")).toBeVisible()
  await page.goBack()
  await expect(welcome).toBeVisible()
  await expect(page.locator(".home-library")).toHaveCount(0)
  await welcome.getByRole("textbox").fill("Build a welcome page without losing this task")
  await expect(welcome.getByRole("combobox")).not.toHaveValue("")
  await welcome.getByRole("button", { name: "Continue to session" }).click()
  await expect(page).toHaveURL(/\/new-session\?draftId=/)
  const composer = page.locator('[data-component="prompt-input"][contenteditable="true"]').first()
  await expect(composer).toContainText("Build a welcome page without losing this task")
  await page.goBack()
  await expect(welcome).toBeVisible()
  await page.goForward()
  await expect(composer).toContainText("Build a welcome page without losing this task")
})

test("welcome stays usable in a narrow viewport", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await mockStressTimeline(page)
  await installTimelineSettings(page)
  await installStressSessionTabs(page)
  await page.goto("/")
  const welcome = page.getByRole("region", { name: "What will we create today?" })
  await expect(welcome.getByRole("textbox")).toBeVisible()
  await expect(welcome.getByRole("button", { name: "Continue to session" })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: "../../quality/desktop-audit-20260909/welcome-narrow.png" })
})
