// Generated by @zaovra-ai/httpapi-codegen. Do not edit.
import { Effect, Stream, Schema } from "effect"
import { Sse } from "effect/unstable/encoding"
import { HttpClientError } from "effect/unstable/http"
import { HttpApiClient } from "effect/unstable/httpapi"
import { ClientApi } from "../contract"
import { ClientError } from "./client-error"

type RawClient = HttpApiClient.ForApi<typeof ClientApi>

const mapClientError = <E>(error: E) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : error

const Endpoint0_0 = (raw: RawClient["server.health"]) => () =>
  raw["health.get"]({}).pipe(Effect.mapError(mapClientError))

const adaptGroup0 = (raw: RawClient["server.health"]) => ({ get: Endpoint0_0(raw) })

type Endpoint1_0Request = Parameters<RawClient["server.location"]["location.get"]>[0]
type Endpoint1_0Input = { readonly location?: Endpoint1_0Request["query"]["location"] }
const Endpoint1_0 = (raw: RawClient["server.location"]) => (input?: Endpoint1_0Input) =>
  raw["location.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup1 = (raw: RawClient["server.location"]) => ({ get: Endpoint1_0(raw) })

type Endpoint2_0Request = Parameters<RawClient["server.agent"]["agent.list"]>[0]
type Endpoint2_0Input = { readonly location?: Endpoint2_0Request["query"]["location"] }
const Endpoint2_0 = (raw: RawClient["server.agent"]) => (input?: Endpoint2_0Input) =>
  raw["agent.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup2 = (raw: RawClient["server.agent"]) => ({ list: Endpoint2_0(raw) })

type Endpoint3_0Request = Parameters<RawClient["server.session"]["session.list"]>[0]
type Endpoint3_0Input = {
  readonly workspace?: Endpoint3_0Request["query"]["workspace"]
  readonly limit?: Endpoint3_0Request["query"]["limit"]
  readonly order?: Endpoint3_0Request["query"]["order"]
  readonly search?: Endpoint3_0Request["query"]["search"]
  readonly roots?: Endpoint3_0Request["query"]["roots"]
  readonly directory?: Endpoint3_0Request["query"]["directory"]
  readonly project?: Endpoint3_0Request["query"]["project"]
  readonly subpath?: Endpoint3_0Request["query"]["subpath"]
  readonly cursor?: Endpoint3_0Request["query"]["cursor"]
}
const Endpoint3_0 = (raw: RawClient["server.session"]) => (input?: Endpoint3_0Input) =>
  raw["session.list"]({
    query: {
      workspace: input?.["workspace"],
      limit: input?.["limit"],
      order: input?.["order"],
      search: input?.["search"],
      roots: input?.["roots"],
      directory: input?.["directory"],
      project: input?.["project"],
      subpath: input?.["subpath"],
      cursor: input?.["cursor"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_1Request = Parameters<RawClient["server.session"]["session.create"]>[0]
type Endpoint3_1Input = {
  readonly id?: Endpoint3_1Request["payload"]["id"]
  readonly agent?: Endpoint3_1Request["payload"]["agent"]
  readonly model?: Endpoint3_1Request["payload"]["model"]
  readonly location?: Endpoint3_1Request["payload"]["location"]
}
const Endpoint3_1 = (raw: RawClient["server.session"]) => (input?: Endpoint3_1Input) =>
  raw["session.create"]({
    payload: { id: input?.["id"], agent: input?.["agent"], model: input?.["model"], location: input?.["location"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const Endpoint3_2 = (raw: RawClient["server.session"]) => () =>
  raw["session.active"]({}).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_3Request = Parameters<RawClient["server.session"]["session.get"]>[0]
type Endpoint3_3Input = { readonly sessionID: Endpoint3_3Request["params"]["sessionID"] }
const Endpoint3_3 = (raw: RawClient["server.session"]) => (input: Endpoint3_3Input) =>
  raw["session.get"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_4Request = Parameters<RawClient["server.session"]["session.switchAgent"]>[0]
type Endpoint3_4Input = {
  readonly sessionID: Endpoint3_4Request["params"]["sessionID"]
  readonly agent: Endpoint3_4Request["payload"]["agent"]
}
const Endpoint3_4 = (raw: RawClient["server.session"]) => (input: Endpoint3_4Input) =>
  raw["session.switchAgent"]({ params: { sessionID: input["sessionID"] }, payload: { agent: input["agent"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint3_5Request = Parameters<RawClient["server.session"]["session.switchModel"]>[0]
type Endpoint3_5Input = {
  readonly sessionID: Endpoint3_5Request["params"]["sessionID"]
  readonly model: Endpoint3_5Request["payload"]["model"]
}
const Endpoint3_5 = (raw: RawClient["server.session"]) => (input: Endpoint3_5Input) =>
  raw["session.switchModel"]({ params: { sessionID: input["sessionID"] }, payload: { model: input["model"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint3_6Request = Parameters<RawClient["server.session"]["session.prompt"]>[0]
type Endpoint3_6Input = {
  readonly sessionID: Endpoint3_6Request["params"]["sessionID"]
  readonly id?: Endpoint3_6Request["payload"]["id"]
  readonly prompt: Endpoint3_6Request["payload"]["prompt"]
  readonly delivery?: Endpoint3_6Request["payload"]["delivery"]
  readonly resume?: Endpoint3_6Request["payload"]["resume"]
}
const Endpoint3_6 = (raw: RawClient["server.session"]) => (input: Endpoint3_6Input) =>
  raw["session.prompt"]({
    params: { sessionID: input["sessionID"] },
    payload: { id: input["id"], prompt: input["prompt"], delivery: input["delivery"], resume: input["resume"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_7Request = Parameters<RawClient["server.session"]["session.pendingInputs"]>[0]
type Endpoint3_7Input = { readonly sessionID: Endpoint3_7Request["params"]["sessionID"] }
const Endpoint3_7 = (raw: RawClient["server.session"]) => (input: Endpoint3_7Input) =>
  raw["session.pendingInputs"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_8Request = Parameters<RawClient["server.session"]["session.shell"]>[0]
type Endpoint3_8Input = {
  readonly sessionID: Endpoint3_8Request["params"]["sessionID"]
  readonly id?: Endpoint3_8Request["payload"]["id"]
  readonly command: Endpoint3_8Request["payload"]["command"]
  readonly resume?: Endpoint3_8Request["payload"]["resume"]
}
const Endpoint3_8 = (raw: RawClient["server.session"]) => (input: Endpoint3_8Input) =>
  raw["session.shell"]({
    params: { sessionID: input["sessionID"] },
    payload: { id: input["id"], command: input["command"], resume: input["resume"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_9Request = Parameters<RawClient["server.session"]["session.todos"]>[0]
type Endpoint3_9Input = { readonly sessionID: Endpoint3_9Request["params"]["sessionID"] }
const Endpoint3_9 = (raw: RawClient["server.session"]) => (input: Endpoint3_9Input) =>
  raw["session.todos"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_10Request = Parameters<RawClient["server.session"]["session.compact"]>[0]
type Endpoint3_10Input = { readonly sessionID: Endpoint3_10Request["params"]["sessionID"] }
const Endpoint3_10 = (raw: RawClient["server.session"]) => (input: Endpoint3_10Input) =>
  raw["session.compact"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_11Request = Parameters<RawClient["server.session"]["session.wait"]>[0]
type Endpoint3_11Input = { readonly sessionID: Endpoint3_11Request["params"]["sessionID"] }
const Endpoint3_11 = (raw: RawClient["server.session"]) => (input: Endpoint3_11Input) =>
  raw["session.wait"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_12Request = Parameters<RawClient["server.session"]["session.revert.stage"]>[0]
type Endpoint3_12Input = {
  readonly sessionID: Endpoint3_12Request["params"]["sessionID"]
  readonly messageID: Endpoint3_12Request["payload"]["messageID"]
  readonly files?: Endpoint3_12Request["payload"]["files"]
}
const Endpoint3_12 = (raw: RawClient["server.session"]) => (input: Endpoint3_12Input) =>
  raw["session.revert.stage"]({
    params: { sessionID: input["sessionID"] },
    payload: { messageID: input["messageID"], files: input["files"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_13Request = Parameters<RawClient["server.session"]["session.revert.clear"]>[0]
type Endpoint3_13Input = { readonly sessionID: Endpoint3_13Request["params"]["sessionID"] }
const Endpoint3_13 = (raw: RawClient["server.session"]) => (input: Endpoint3_13Input) =>
  raw["session.revert.clear"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_14Request = Parameters<RawClient["server.session"]["session.revert.commit"]>[0]
type Endpoint3_14Input = { readonly sessionID: Endpoint3_14Request["params"]["sessionID"] }
const Endpoint3_14 = (raw: RawClient["server.session"]) => (input: Endpoint3_14Input) =>
  raw["session.revert.commit"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_15Request = Parameters<RawClient["server.session"]["session.context"]>[0]
type Endpoint3_15Input = { readonly sessionID: Endpoint3_15Request["params"]["sessionID"] }
const Endpoint3_15 = (raw: RawClient["server.session"]) => (input: Endpoint3_15Input) =>
  raw["session.context"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_16Request = Parameters<RawClient["server.session"]["session.history"]>[0]
type Endpoint3_16Input = {
  readonly sessionID: Endpoint3_16Request["params"]["sessionID"]
  readonly limit?: Endpoint3_16Request["query"]["limit"]
  readonly after?: Endpoint3_16Request["query"]["after"]
}
const Endpoint3_16 = (raw: RawClient["server.session"]) => (input: Endpoint3_16Input) =>
  raw["session.history"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], after: input["after"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_17Request = Parameters<RawClient["server.session"]["session.events"]>[0]
type Endpoint3_17Input = {
  readonly sessionID: Endpoint3_17Request["params"]["sessionID"]
  readonly after?: Endpoint3_17Request["query"]["after"]
}
const Endpoint3_17 = (raw: RawClient["server.session"]) => (input: Endpoint3_17Input) =>
  Stream.unwrap(
    raw["session.events"]({ params: { sessionID: input["sessionID"] }, query: { after: input["after"] } }).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

type Endpoint3_18Request = Parameters<RawClient["server.session"]["session.interrupt"]>[0]
type Endpoint3_18Input = { readonly sessionID: Endpoint3_18Request["params"]["sessionID"] }
const Endpoint3_18 = (raw: RawClient["server.session"]) => (input: Endpoint3_18Input) =>
  raw["session.interrupt"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_19Request = Parameters<RawClient["server.session"]["session.message"]>[0]
type Endpoint3_19Input = {
  readonly sessionID: Endpoint3_19Request["params"]["sessionID"]
  readonly messageID: Endpoint3_19Request["params"]["messageID"]
}
const Endpoint3_19 = (raw: RawClient["server.session"]) => (input: Endpoint3_19Input) =>
  raw["session.message"]({ params: { sessionID: input["sessionID"], messageID: input["messageID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_20Request = Parameters<RawClient["server.session"]["session.update"]>[0]
type Endpoint3_20Input = {
  readonly sessionID: Endpoint3_20Request["params"]["sessionID"]
  readonly title?: Endpoint3_20Request["payload"]["title"]
  readonly archived?: Endpoint3_20Request["payload"]["archived"]
}
const Endpoint3_20 = (raw: RawClient["server.session"]) => (input: Endpoint3_20Input) =>
  raw["session.update"]({
    params: { sessionID: input["sessionID"] },
    payload: { title: input["title"], archived: input["archived"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_21Request = Parameters<RawClient["server.session"]["session.remove"]>[0]
type Endpoint3_21Input = { readonly sessionID: Endpoint3_21Request["params"]["sessionID"] }
const Endpoint3_21 = (raw: RawClient["server.session"]) => (input: Endpoint3_21Input) =>
  raw["session.remove"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup3 = (raw: RawClient["server.session"]) => ({
  list: Endpoint3_0(raw),
  create: Endpoint3_1(raw),
  active: Endpoint3_2(raw),
  get: Endpoint3_3(raw),
  switchAgent: Endpoint3_4(raw),
  switchModel: Endpoint3_5(raw),
  prompt: Endpoint3_6(raw),
  pendingInputs: Endpoint3_7(raw),
  shell: Endpoint3_8(raw),
  todos: Endpoint3_9(raw),
  compact: Endpoint3_10(raw),
  wait: Endpoint3_11(raw),
  stage: Endpoint3_12(raw),
  clear: Endpoint3_13(raw),
  commit: Endpoint3_14(raw),
  context: Endpoint3_15(raw),
  history: Endpoint3_16(raw),
  events: Endpoint3_17(raw),
  interrupt: Endpoint3_18(raw),
  message: Endpoint3_19(raw),
  update: Endpoint3_20(raw),
  remove: Endpoint3_21(raw),
})

const Endpoint4_0 = (raw: RawClient["server.work"]) => () =>
  raw["work.list"]({}).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_1Request = Parameters<RawClient["server.work"]["work.create"]>[0]
type Endpoint4_1Input = {
  readonly id?: Endpoint4_1Request["payload"]["id"]
  readonly location: Endpoint4_1Request["payload"]["location"]
  readonly objective: Endpoint4_1Request["payload"]["objective"]
  readonly acceptanceCriteria: Endpoint4_1Request["payload"]["acceptanceCriteria"]
  readonly budget?: Endpoint4_1Request["payload"]["budget"]
  readonly planning?: Endpoint4_1Request["payload"]["planning"]
  readonly tasks?: Endpoint4_1Request["payload"]["tasks"]
}
const Endpoint4_1 = (raw: RawClient["server.work"]) => (input: Endpoint4_1Input) =>
  raw["work.create"]({
    payload: {
      id: input["id"],
      location: input["location"],
      objective: input["objective"],
      acceptanceCriteria: input["acceptanceCriteria"],
      budget: input["budget"],
      planning: input["planning"],
      tasks: input["tasks"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const Endpoint4_2 = (raw: RawClient["server.work"]) => () =>
  raw["work.active"]({}).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const Endpoint4_3 = (raw: RawClient["server.work"]) => () =>
  raw["work.artifacts"]({}).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_4Request = Parameters<RawClient["server.work"]["work.artifactCollect"]>[0]
type Endpoint4_4Input = {
  readonly minimumAgeMs: Endpoint4_4Request["payload"]["minimumAgeMs"]
  readonly dryRun: Endpoint4_4Request["payload"]["dryRun"]
  readonly limit?: Endpoint4_4Request["payload"]["limit"]
}
const Endpoint4_4 = (raw: RawClient["server.work"]) => (input: Endpoint4_4Input) =>
  raw["work.artifactCollect"]({
    payload: { minimumAgeMs: input["minimumAgeMs"], dryRun: input["dryRun"], limit: input["limit"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_5Request = Parameters<RawClient["server.work"]["work.get"]>[0]
type Endpoint4_5Input = { readonly goalID: Endpoint4_5Request["params"]["goalID"] }
const Endpoint4_5 = (raw: RawClient["server.work"]) => (input: Endpoint4_5Input) =>
  raw["work.get"]({ params: { goalID: input["goalID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_6Request = Parameters<RawClient["server.work"]["work.expand"]>[0]
type Endpoint4_6Input = {
  readonly goalID: Endpoint4_6Request["params"]["goalID"]
  readonly tasks: Endpoint4_6Request["payload"]["tasks"]
}
const Endpoint4_6 = (raw: RawClient["server.work"]) => (input: Endpoint4_6Input) =>
  raw["work.expand"]({ params: { goalID: input["goalID"] }, payload: { tasks: input["tasks"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_7Request = Parameters<RawClient["server.work"]["work.replan"]>[0]
type Endpoint4_7Input = {
  readonly goalID: Endpoint4_7Request["params"]["goalID"]
  readonly taskID: Endpoint4_7Request["payload"]["taskID"]
  readonly reason: Endpoint4_7Request["payload"]["reason"]
}
const Endpoint4_7 = (raw: RawClient["server.work"]) => (input: Endpoint4_7Input) =>
  raw["work.replan"]({
    params: { goalID: input["goalID"] },
    payload: { taskID: input["taskID"], reason: input["reason"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_8Request = Parameters<RawClient["server.work"]["work.resume"]>[0]
type Endpoint4_8Input = { readonly goalID: Endpoint4_8Request["params"]["goalID"] }
const Endpoint4_8 = (raw: RawClient["server.work"]) => (input: Endpoint4_8Input) =>
  raw["work.resume"]({ params: { goalID: input["goalID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_9Request = Parameters<RawClient["server.work"]["work.pause"]>[0]
type Endpoint4_9Input = { readonly goalID: Endpoint4_9Request["params"]["goalID"] }
const Endpoint4_9 = (raw: RawClient["server.work"]) => (input: Endpoint4_9Input) =>
  raw["work.pause"]({ params: { goalID: input["goalID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_10Request = Parameters<RawClient["server.work"]["work.cancel"]>[0]
type Endpoint4_10Input = {
  readonly goalID: Endpoint4_10Request["params"]["goalID"]
  readonly reason?: Endpoint4_10Request["payload"]["reason"]
}
const Endpoint4_10 = (raw: RawClient["server.work"]) => (input: Endpoint4_10Input) =>
  raw["work.cancel"]({ params: { goalID: input["goalID"] }, payload: { reason: input["reason"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint4_11Request = Parameters<RawClient["server.work"]["work.resolveUnknown"]>[0]
type Endpoint4_11Input = {
  readonly goalID: Endpoint4_11Request["params"]["goalID"]
  readonly attemptID: Endpoint4_11Request["params"]["attemptID"]
  readonly resolution: Endpoint4_11Request["payload"]["resolution"]
  readonly reason?: Endpoint4_11Request["payload"]["reason"]
}
const Endpoint4_11 = (raw: RawClient["server.work"]) => (input: Endpoint4_11Input) =>
  raw["work.resolveUnknown"]({
    params: { goalID: input["goalID"], attemptID: input["attemptID"] },
    payload: { resolution: input["resolution"], reason: input["reason"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_12Request = Parameters<RawClient["server.work"]["work.resolveMemory"]>[0]
type Endpoint4_12Input = {
  readonly goalID: Endpoint4_12Request["params"]["goalID"]
  readonly key: Endpoint4_12Request["payload"]["key"]
  readonly handoffID: Endpoint4_12Request["payload"]["handoffID"]
  readonly itemDigest: Endpoint4_12Request["payload"]["itemDigest"]
  readonly reason?: Endpoint4_12Request["payload"]["reason"]
}
const Endpoint4_12 = (raw: RawClient["server.work"]) => (input: Endpoint4_12Input) =>
  raw["work.resolveMemory"]({
    params: { goalID: input["goalID"] },
    payload: {
      key: input["key"],
      handoffID: input["handoffID"],
      itemDigest: input["itemDigest"],
      reason: input["reason"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_13Request = Parameters<RawClient["server.work"]["work.updateMemory"]>[0]
type Endpoint4_13Input = {
  readonly goalID: Endpoint4_13Request["params"]["goalID"]
  readonly key: Endpoint4_13Request["params"]["key"]
  readonly kind: Endpoint4_13Request["payload"]["kind"]
  readonly text: Endpoint4_13Request["payload"]["text"]
  readonly reference?: Endpoint4_13Request["payload"]["reference"]
  readonly reason?: Endpoint4_13Request["payload"]["reason"]
}
const Endpoint4_13 = (raw: RawClient["server.work"]) => (input: Endpoint4_13Input) =>
  raw["work.updateMemory"]({
    params: { goalID: input["goalID"], key: input["key"] },
    payload: { kind: input["kind"], text: input["text"], reference: input["reference"], reason: input["reason"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_14Request = Parameters<RawClient["server.work"]["work.deleteMemory"]>[0]
type Endpoint4_14Input = {
  readonly goalID: Endpoint4_14Request["params"]["goalID"]
  readonly key: Endpoint4_14Request["params"]["key"]
}
const Endpoint4_14 = (raw: RawClient["server.work"]) => (input: Endpoint4_14Input) =>
  raw["work.deleteMemory"]({ params: { goalID: input["goalID"], key: input["key"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const adaptGroup4 = (raw: RawClient["server.work"]) => ({
  list: Endpoint4_0(raw),
  create: Endpoint4_1(raw),
  active: Endpoint4_2(raw),
  artifacts: Endpoint4_3(raw),
  artifactCollect: Endpoint4_4(raw),
  get: Endpoint4_5(raw),
  expand: Endpoint4_6(raw),
  replan: Endpoint4_7(raw),
  resume: Endpoint4_8(raw),
  pause: Endpoint4_9(raw),
  cancel: Endpoint4_10(raw),
  resolveUnknown: Endpoint4_11(raw),
  resolveMemory: Endpoint4_12(raw),
  updateMemory: Endpoint4_13(raw),
  deleteMemory: Endpoint4_14(raw),
})

type Endpoint5_0Request = Parameters<RawClient["server.message"]["session.messages"]>[0]
type Endpoint5_0Input = {
  readonly sessionID: Endpoint5_0Request["params"]["sessionID"]
  readonly limit?: Endpoint5_0Request["query"]["limit"]
  readonly order?: Endpoint5_0Request["query"]["order"]
  readonly cursor?: Endpoint5_0Request["query"]["cursor"]
}
const Endpoint5_0 = (raw: RawClient["server.message"]) => (input: Endpoint5_0Input) =>
  raw["session.messages"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], order: input["order"], cursor: input["cursor"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup5 = (raw: RawClient["server.message"]) => ({ list: Endpoint5_0(raw) })

type Endpoint6_0Request = Parameters<RawClient["server.model"]["model.list"]>[0]
type Endpoint6_0Input = { readonly location?: Endpoint6_0Request["query"]["location"] }
const Endpoint6_0 = (raw: RawClient["server.model"]) => (input?: Endpoint6_0Input) =>
  raw["model.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup6 = (raw: RawClient["server.model"]) => ({ list: Endpoint6_0(raw) })

type Endpoint7_0Request = Parameters<RawClient["server.provider"]["provider.list"]>[0]
type Endpoint7_0Input = { readonly location?: Endpoint7_0Request["query"]["location"] }
const Endpoint7_0 = (raw: RawClient["server.provider"]) => (input?: Endpoint7_0Input) =>
  raw["provider.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint7_1Request = Parameters<RawClient["server.provider"]["provider.get"]>[0]
type Endpoint7_1Input = {
  readonly providerID: Endpoint7_1Request["params"]["providerID"]
  readonly location?: Endpoint7_1Request["query"]["location"]
}
const Endpoint7_1 = (raw: RawClient["server.provider"]) => (input: Endpoint7_1Input) =>
  raw["provider.get"]({ params: { providerID: input["providerID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup7 = (raw: RawClient["server.provider"]) => ({ list: Endpoint7_0(raw), get: Endpoint7_1(raw) })

type Endpoint8_0Request = Parameters<RawClient["server.integration"]["integration.list"]>[0]
type Endpoint8_0Input = { readonly location?: Endpoint8_0Request["query"]["location"] }
const Endpoint8_0 = (raw: RawClient["server.integration"]) => (input?: Endpoint8_0Input) =>
  raw["integration.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint8_1Request = Parameters<RawClient["server.integration"]["integration.get"]>[0]
type Endpoint8_1Input = {
  readonly integrationID: Endpoint8_1Request["params"]["integrationID"]
  readonly location?: Endpoint8_1Request["query"]["location"]
}
const Endpoint8_1 = (raw: RawClient["server.integration"]) => (input: Endpoint8_1Input) =>
  raw["integration.get"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_2Request = Parameters<RawClient["server.integration"]["integration.connect.key"]>[0]
type Endpoint8_2Input = {
  readonly integrationID: Endpoint8_2Request["params"]["integrationID"]
  readonly location?: Endpoint8_2Request["query"]["location"]
  readonly key: Endpoint8_2Request["payload"]["key"]
  readonly inputs?: Endpoint8_2Request["payload"]["inputs"]
  readonly label?: Endpoint8_2Request["payload"]["label"]
}
const Endpoint8_2 = (raw: RawClient["server.integration"]) => (input: Endpoint8_2Input) =>
  raw["integration.connect.key"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { key: input["key"], inputs: input["inputs"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_3Request = Parameters<RawClient["server.integration"]["integration.connect.oauth"]>[0]
type Endpoint8_3Input = {
  readonly integrationID: Endpoint8_3Request["params"]["integrationID"]
  readonly location?: Endpoint8_3Request["query"]["location"]
  readonly methodID: Endpoint8_3Request["payload"]["methodID"]
  readonly inputs: Endpoint8_3Request["payload"]["inputs"]
  readonly label?: Endpoint8_3Request["payload"]["label"]
}
const Endpoint8_3 = (raw: RawClient["server.integration"]) => (input: Endpoint8_3Input) =>
  raw["integration.connect.oauth"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { methodID: input["methodID"], inputs: input["inputs"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_4Request = Parameters<RawClient["server.integration"]["integration.attempt.status"]>[0]
type Endpoint8_4Input = {
  readonly attemptID: Endpoint8_4Request["params"]["attemptID"]
  readonly location?: Endpoint8_4Request["query"]["location"]
}
const Endpoint8_4 = (raw: RawClient["server.integration"]) => (input: Endpoint8_4Input) =>
  raw["integration.attempt.status"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_5Request = Parameters<RawClient["server.integration"]["integration.attempt.complete"]>[0]
type Endpoint8_5Input = {
  readonly attemptID: Endpoint8_5Request["params"]["attemptID"]
  readonly location?: Endpoint8_5Request["query"]["location"]
  readonly code?: Endpoint8_5Request["payload"]["code"]
}
const Endpoint8_5 = (raw: RawClient["server.integration"]) => (input: Endpoint8_5Input) =>
  raw["integration.attempt.complete"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
    payload: { code: input["code"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_6Request = Parameters<RawClient["server.integration"]["integration.attempt.cancel"]>[0]
type Endpoint8_6Input = {
  readonly attemptID: Endpoint8_6Request["params"]["attemptID"]
  readonly location?: Endpoint8_6Request["query"]["location"]
}
const Endpoint8_6 = (raw: RawClient["server.integration"]) => (input: Endpoint8_6Input) =>
  raw["integration.attempt.cancel"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup8 = (raw: RawClient["server.integration"]) => ({
  list: Endpoint8_0(raw),
  get: Endpoint8_1(raw),
  connectKey: Endpoint8_2(raw),
  connectOauth: Endpoint8_3(raw),
  attemptStatus: Endpoint8_4(raw),
  attemptComplete: Endpoint8_5(raw),
  attemptCancel: Endpoint8_6(raw),
})

type Endpoint9_0Request = Parameters<RawClient["server.credential"]["credential.update"]>[0]
type Endpoint9_0Input = {
  readonly credentialID: Endpoint9_0Request["params"]["credentialID"]
  readonly location?: Endpoint9_0Request["query"]["location"]
  readonly label: Endpoint9_0Request["payload"]["label"]
}
const Endpoint9_0 = (raw: RawClient["server.credential"]) => (input: Endpoint9_0Input) =>
  raw["credential.update"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
    payload: { label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint9_1Request = Parameters<RawClient["server.credential"]["credential.remove"]>[0]
type Endpoint9_1Input = {
  readonly credentialID: Endpoint9_1Request["params"]["credentialID"]
  readonly location?: Endpoint9_1Request["query"]["location"]
}
const Endpoint9_1 = (raw: RawClient["server.credential"]) => (input: Endpoint9_1Input) =>
  raw["credential.remove"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup9 = (raw: RawClient["server.credential"]) => ({ update: Endpoint9_0(raw), remove: Endpoint9_1(raw) })

type Endpoint10_0Request = Parameters<RawClient["server.mcp"]["mcp.status"]>[0]
type Endpoint10_0Input = { readonly location?: Endpoint10_0Request["query"]["location"] }
const Endpoint10_0 = (raw: RawClient["server.mcp"]) => (input?: Endpoint10_0Input) =>
  raw["mcp.status"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint10_1Request = Parameters<RawClient["server.mcp"]["mcp.resources"]>[0]
type Endpoint10_1Input = { readonly location?: Endpoint10_1Request["query"]["location"] }
const Endpoint10_1 = (raw: RawClient["server.mcp"]) => (input?: Endpoint10_1Input) =>
  raw["mcp.resources"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint10_2Request = Parameters<RawClient["server.mcp"]["mcp.connect"]>[0]
type Endpoint10_2Input = {
  readonly name: Endpoint10_2Request["params"]["name"]
  readonly location?: Endpoint10_2Request["query"]["location"]
}
const Endpoint10_2 = (raw: RawClient["server.mcp"]) => (input: Endpoint10_2Input) =>
  raw["mcp.connect"]({ params: { name: input["name"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint10_3Request = Parameters<RawClient["server.mcp"]["mcp.disconnect"]>[0]
type Endpoint10_3Input = {
  readonly name: Endpoint10_3Request["params"]["name"]
  readonly location?: Endpoint10_3Request["query"]["location"]
}
const Endpoint10_3 = (raw: RawClient["server.mcp"]) => (input: Endpoint10_3Input) =>
  raw["mcp.disconnect"]({ params: { name: input["name"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup10 = (raw: RawClient["server.mcp"]) => ({
  status: Endpoint10_0(raw),
  resources: Endpoint10_1(raw),
  connect: Endpoint10_2(raw),
  disconnect: Endpoint10_3(raw),
})

type Endpoint11_0Request = Parameters<RawClient["server.permission"]["permission.request.list"]>[0]
type Endpoint11_0Input = { readonly location?: Endpoint11_0Request["query"]["location"] }
const Endpoint11_0 = (raw: RawClient["server.permission"]) => (input?: Endpoint11_0Input) =>
  raw["permission.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint11_1Request = Parameters<RawClient["server.permission"]["permission.saved.list"]>[0]
type Endpoint11_1Input = { readonly projectID?: Endpoint11_1Request["query"]["projectID"] }
const Endpoint11_1 = (raw: RawClient["server.permission"]) => (input?: Endpoint11_1Input) =>
  raw["permission.saved.list"]({ query: { projectID: input?.["projectID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint11_2Request = Parameters<RawClient["server.permission"]["permission.saved.remove"]>[0]
type Endpoint11_2Input = { readonly id: Endpoint11_2Request["params"]["id"] }
const Endpoint11_2 = (raw: RawClient["server.permission"]) => (input: Endpoint11_2Input) =>
  raw["permission.saved.remove"]({ params: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint11_3Request = Parameters<RawClient["server.permission"]["session.permission.create"]>[0]
type Endpoint11_3Input = {
  readonly sessionID: Endpoint11_3Request["params"]["sessionID"]
  readonly id?: Endpoint11_3Request["payload"]["id"]
  readonly action: Endpoint11_3Request["payload"]["action"]
  readonly resources: Endpoint11_3Request["payload"]["resources"]
  readonly save?: Endpoint11_3Request["payload"]["save"]
  readonly metadata?: Endpoint11_3Request["payload"]["metadata"]
  readonly source?: Endpoint11_3Request["payload"]["source"]
  readonly agent?: Endpoint11_3Request["payload"]["agent"]
}
const Endpoint11_3 = (raw: RawClient["server.permission"]) => (input: Endpoint11_3Input) =>
  raw["session.permission.create"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      action: input["action"],
      resources: input["resources"],
      save: input["save"],
      metadata: input["metadata"],
      source: input["source"],
      agent: input["agent"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint11_4Request = Parameters<RawClient["server.permission"]["session.permission.list"]>[0]
type Endpoint11_4Input = { readonly sessionID: Endpoint11_4Request["params"]["sessionID"] }
const Endpoint11_4 = (raw: RawClient["server.permission"]) => (input: Endpoint11_4Input) =>
  raw["session.permission.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint11_5Request = Parameters<RawClient["server.permission"]["session.permission.get"]>[0]
type Endpoint11_5Input = {
  readonly sessionID: Endpoint11_5Request["params"]["sessionID"]
  readonly requestID: Endpoint11_5Request["params"]["requestID"]
}
const Endpoint11_5 = (raw: RawClient["server.permission"]) => (input: Endpoint11_5Input) =>
  raw["session.permission.get"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint11_6Request = Parameters<RawClient["server.permission"]["session.permission.reply"]>[0]
type Endpoint11_6Input = {
  readonly sessionID: Endpoint11_6Request["params"]["sessionID"]
  readonly requestID: Endpoint11_6Request["params"]["requestID"]
  readonly reply: Endpoint11_6Request["payload"]["reply"]
  readonly message?: Endpoint11_6Request["payload"]["message"]
}
const Endpoint11_6 = (raw: RawClient["server.permission"]) => (input: Endpoint11_6Input) =>
  raw["session.permission.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { reply: input["reply"], message: input["message"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup11 = (raw: RawClient["server.permission"]) => ({
  listRequests: Endpoint11_0(raw),
  listSaved: Endpoint11_1(raw),
  removeSaved: Endpoint11_2(raw),
  create: Endpoint11_3(raw),
  list: Endpoint11_4(raw),
  get: Endpoint11_5(raw),
  reply: Endpoint11_6(raw),
})

type Endpoint12_0Request = Parameters<RawClient["server.fs"]["fs.list"]>[0]
type Endpoint12_0Input = {
  readonly location?: Endpoint12_0Request["query"]["location"]
  readonly path?: Endpoint12_0Request["query"]["path"]
}
const Endpoint12_0 = (raw: RawClient["server.fs"]) => (input?: Endpoint12_0Input) =>
  raw["fs.list"]({ query: { location: input?.["location"], path: input?.["path"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint12_1Request = Parameters<RawClient["server.fs"]["fs.find"]>[0]
type Endpoint12_1Input = {
  readonly location?: Endpoint12_1Request["query"]["location"]
  readonly query: Endpoint12_1Request["query"]["query"]
  readonly type?: Endpoint12_1Request["query"]["type"]
  readonly limit?: Endpoint12_1Request["query"]["limit"]
}
const Endpoint12_1 = (raw: RawClient["server.fs"]) => (input: Endpoint12_1Input) =>
  raw["fs.find"]({
    query: { location: input["location"], query: input["query"], type: input["type"], limit: input["limit"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup12 = (raw: RawClient["server.fs"]) => ({ list: Endpoint12_0(raw), find: Endpoint12_1(raw) })

type Endpoint13_0Request = Parameters<RawClient["server.command"]["command.list"]>[0]
type Endpoint13_0Input = { readonly location?: Endpoint13_0Request["query"]["location"] }
const Endpoint13_0 = (raw: RawClient["server.command"]) => (input?: Endpoint13_0Input) =>
  raw["command.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup13 = (raw: RawClient["server.command"]) => ({ list: Endpoint13_0(raw) })

type Endpoint14_0Request = Parameters<RawClient["server.skill"]["skill.list"]>[0]
type Endpoint14_0Input = { readonly location?: Endpoint14_0Request["query"]["location"] }
const Endpoint14_0 = (raw: RawClient["server.skill"]) => (input?: Endpoint14_0Input) =>
  raw["skill.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup14 = (raw: RawClient["server.skill"]) => ({ list: Endpoint14_0(raw) })

const Endpoint15_0 = (raw: RawClient["server.event"]) => () =>
  Stream.unwrap(
    raw["event.subscribe"]({}).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

const adaptGroup15 = (raw: RawClient["server.event"]) => ({ subscribe: Endpoint15_0(raw) })

type Endpoint16_0Request = Parameters<RawClient["server.pty"]["pty.list"]>[0]
type Endpoint16_0Input = { readonly location?: Endpoint16_0Request["query"]["location"] }
const Endpoint16_0 = (raw: RawClient["server.pty"]) => (input?: Endpoint16_0Input) =>
  raw["pty.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint16_1Request = Parameters<RawClient["server.pty"]["pty.create"]>[0]
type Endpoint16_1Input = {
  readonly location?: Endpoint16_1Request["query"]["location"]
  readonly command?: Endpoint16_1Request["payload"]["command"]
  readonly args?: Endpoint16_1Request["payload"]["args"]
  readonly cwd?: Endpoint16_1Request["payload"]["cwd"]
  readonly title?: Endpoint16_1Request["payload"]["title"]
  readonly env?: Endpoint16_1Request["payload"]["env"]
}
const Endpoint16_1 = (raw: RawClient["server.pty"]) => (input?: Endpoint16_1Input) =>
  raw["pty.create"]({
    query: { location: input?.["location"] },
    payload: {
      command: input?.["command"],
      args: input?.["args"],
      cwd: input?.["cwd"],
      title: input?.["title"],
      env: input?.["env"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint16_2Request = Parameters<RawClient["server.pty"]["pty.get"]>[0]
type Endpoint16_2Input = {
  readonly ptyID: Endpoint16_2Request["params"]["ptyID"]
  readonly location?: Endpoint16_2Request["query"]["location"]
}
const Endpoint16_2 = (raw: RawClient["server.pty"]) => (input: Endpoint16_2Input) =>
  raw["pty.get"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint16_3Request = Parameters<RawClient["server.pty"]["pty.update"]>[0]
type Endpoint16_3Input = {
  readonly ptyID: Endpoint16_3Request["params"]["ptyID"]
  readonly location?: Endpoint16_3Request["query"]["location"]
  readonly title?: Endpoint16_3Request["payload"]["title"]
  readonly size?: Endpoint16_3Request["payload"]["size"]
}
const Endpoint16_3 = (raw: RawClient["server.pty"]) => (input: Endpoint16_3Input) =>
  raw["pty.update"]({
    params: { ptyID: input["ptyID"] },
    query: { location: input["location"] },
    payload: { title: input["title"], size: input["size"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint16_4Request = Parameters<RawClient["server.pty"]["pty.remove"]>[0]
type Endpoint16_4Input = {
  readonly ptyID: Endpoint16_4Request["params"]["ptyID"]
  readonly location?: Endpoint16_4Request["query"]["location"]
}
const Endpoint16_4 = (raw: RawClient["server.pty"]) => (input: Endpoint16_4Input) =>
  raw["pty.remove"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup16 = (raw: RawClient["server.pty"]) => ({
  list: Endpoint16_0(raw),
  create: Endpoint16_1(raw),
  get: Endpoint16_2(raw),
  update: Endpoint16_3(raw),
  remove: Endpoint16_4(raw),
})

type Endpoint17_0Request = Parameters<RawClient["server.question"]["question.request.list"]>[0]
type Endpoint17_0Input = { readonly location?: Endpoint17_0Request["query"]["location"] }
const Endpoint17_0 = (raw: RawClient["server.question"]) => (input?: Endpoint17_0Input) =>
  raw["question.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint17_1Request = Parameters<RawClient["server.question"]["session.question.list"]>[0]
type Endpoint17_1Input = { readonly sessionID: Endpoint17_1Request["params"]["sessionID"] }
const Endpoint17_1 = (raw: RawClient["server.question"]) => (input: Endpoint17_1Input) =>
  raw["session.question.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint17_2Request = Parameters<RawClient["server.question"]["session.question.reply"]>[0]
type Endpoint17_2Input = {
  readonly sessionID: Endpoint17_2Request["params"]["sessionID"]
  readonly requestID: Endpoint17_2Request["params"]["requestID"]
  readonly answers: Endpoint17_2Request["payload"]["answers"]
}
const Endpoint17_2 = (raw: RawClient["server.question"]) => (input: Endpoint17_2Input) =>
  raw["session.question.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { answers: input["answers"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint17_3Request = Parameters<RawClient["server.question"]["session.question.reject"]>[0]
type Endpoint17_3Input = {
  readonly sessionID: Endpoint17_3Request["params"]["sessionID"]
  readonly requestID: Endpoint17_3Request["params"]["requestID"]
}
const Endpoint17_3 = (raw: RawClient["server.question"]) => (input: Endpoint17_3Input) =>
  raw["session.question.reject"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup17 = (raw: RawClient["server.question"]) => ({
  listRequests: Endpoint17_0(raw),
  list: Endpoint17_1(raw),
  reply: Endpoint17_2(raw),
  reject: Endpoint17_3(raw),
})

type Endpoint18_0Request = Parameters<RawClient["server.reference"]["reference.list"]>[0]
type Endpoint18_0Input = { readonly location?: Endpoint18_0Request["query"]["location"] }
const Endpoint18_0 = (raw: RawClient["server.reference"]) => (input?: Endpoint18_0Input) =>
  raw["reference.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup18 = (raw: RawClient["server.reference"]) => ({ list: Endpoint18_0(raw) })

type Endpoint19_0Request = Parameters<RawClient["server.projectCopy"]["projectCopy.create"]>[0]
type Endpoint19_0Input = {
  readonly projectID: Endpoint19_0Request["params"]["projectID"]
  readonly location?: Endpoint19_0Request["query"]["location"]
  readonly strategy: Endpoint19_0Request["payload"]["strategy"]
  readonly directory: Endpoint19_0Request["payload"]["directory"]
  readonly name?: Endpoint19_0Request["payload"]["name"]
}
const Endpoint19_0 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint19_0Input) =>
  raw["projectCopy.create"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { strategy: input["strategy"], directory: input["directory"], name: input["name"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_1Request = Parameters<RawClient["server.projectCopy"]["projectCopy.remove"]>[0]
type Endpoint19_1Input = {
  readonly projectID: Endpoint19_1Request["params"]["projectID"]
  readonly location?: Endpoint19_1Request["query"]["location"]
  readonly directory: Endpoint19_1Request["payload"]["directory"]
  readonly force: Endpoint19_1Request["payload"]["force"]
}
const Endpoint19_1 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint19_1Input) =>
  raw["projectCopy.remove"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { directory: input["directory"], force: input["force"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_2Request = Parameters<RawClient["server.projectCopy"]["projectCopy.refresh"]>[0]
type Endpoint19_2Input = {
  readonly projectID: Endpoint19_2Request["params"]["projectID"]
  readonly location?: Endpoint19_2Request["query"]["location"]
}
const Endpoint19_2 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint19_2Input) =>
  raw["projectCopy.refresh"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup19 = (raw: RawClient["server.projectCopy"]) => ({
  create: Endpoint19_0(raw),
  remove: Endpoint19_1(raw),
  refresh: Endpoint19_2(raw),
})

const adaptClient = (raw: RawClient) => ({
  health: adaptGroup0(raw["server.health"]),
  location: adaptGroup1(raw["server.location"]),
  agents: adaptGroup2(raw["server.agent"]),
  sessions: adaptGroup3(raw["server.session"]),
  work: adaptGroup4(raw["server.work"]),
  messages: adaptGroup5(raw["server.message"]),
  models: adaptGroup6(raw["server.model"]),
  providers: adaptGroup7(raw["server.provider"]),
  integrations: adaptGroup8(raw["server.integration"]),
  credentials: adaptGroup9(raw["server.credential"]),
  mcp: adaptGroup10(raw["server.mcp"]),
  permissions: adaptGroup11(raw["server.permission"]),
  files: adaptGroup12(raw["server.fs"]),
  commands: adaptGroup13(raw["server.command"]),
  skills: adaptGroup14(raw["server.skill"]),
  events: adaptGroup15(raw["server.event"]),
  ptys: adaptGroup16(raw["server.pty"]),
  questions: adaptGroup17(raw["server.question"]),
  references: adaptGroup18(raw["server.reference"]),
  projectCopies: adaptGroup19(raw["server.projectCopy"]),
})

export const make = (options?: { readonly baseUrl?: URL | string }) =>
  HttpApiClient.make(ClientApi, options).pipe(Effect.map(adaptClient))
