name: beta

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  sync:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup Git Committer
        id: setup-git-committer
        uses: ./.github/actions/setup-git-committer
        with:
          zaovra-app-id: ${{ vars.ZAOVRA_APP_ID }}
          zaovra-app-secret: ${{ secrets.ZAOVRA_APP_SECRET }}

      - name: Install Zaovra
        run: bun i -g zaovra-ai

      - name: Sync beta branch
        env:
          GH_TOKEN: ${{ steps.setup-git-committer.outputs.token }}
          ZAOVRA_API_KEY: ${{ secrets.ZAOVRA_API_KEY }}
        run: bun script/beta.ts
