name: zaovra

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  zaovra:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /zaovra') ||
      startsWith(github.event.comment.body, '/zaovra')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: ./.github/actions/setup-bun

      - name: Run zaovra
        uses: zuozizuozi/p-zaovra/github@2c14fc5586fe0b88e5c04732d2e846769cc35671 # latest
        env:
          ZAOVRA_API_KEY: ${{ secrets.ZAOVRA_API_KEY }}
          ZAOVRA_PERMISSION: '{"bash": "deny"}'
        with:
          model: zaovra/claude-opus-4-5
